spring.application.name=book
spring.datasource.url=jdbc:postgresql://localhost:5432/take_home_test
spring.datasource.username=postgres
spring.datasource.password=post123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

## untuk mengaktifkan redis ubah menjadi "redis"
spring.cache.type=none